services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    restart: unless-stopped
  backend:
    build: ./backend
    depends_on:
      - database
    env_file: secrets/.env
    environment:
      MODULE_NAME: resslab_tools.main
      FORWARDED_ALLOW_IPS: "*"
      CORS_ENABLED: "true"
      DATABASE_HOST: database
      ROOT_PATH: /api
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
    restart: unless-stopped
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/.env
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: {}
