"""

Revision ID: 6e55058bdd90
Revises: 8ab89d0379ae
Create Date: 2021-12-09 22:13:55.301976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e55058bdd90'
down_revision = '8ab89d0379ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('lat', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('connection', sa.Column('lon', sa.Numeric(precision=8, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'lon')
    op.drop_column('connection', 'lat')
    # ### end Alembic commands ###
