"""kodjo_change

Revision ID: 831689a67e44
Revises: 6e55058bdd90
Create Date: 2021-12-13 16:14:11.316620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831689a67e44'
down_revision = '6e55058bdd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
