"""create connection_panel_zone

Revision ID: 88c82cc44214
Revises: 989b6f552169
Create Date: 2021-11-23 11:12:59.077591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c82cc44214'
down_revision = '989b6f552169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_panel_zone',
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shear_distortion', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('shear_force', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.PrimaryKeyConstraint('connection_id', 'id')
    )
    op.create_index(op.f('ix_connection_panel_zone_connection_id'), 'connection_panel_zone', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_panel_zone_connection_id'), table_name='connection_panel_zone')
    op.drop_table('connection_panel_zone')
    # ### end Alembic commands ###
