"""update connection

Revision ID: 8ab89d0379ae
Revises: 88c82cc44214
Create Date: 2021-11-25 15:02:25.745127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab89d0379ae'
down_revision = '88c82cc44214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('d_b', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('connection', sa.Column('steel_b', sa.String(), nullable=True))
    op.add_column('connection', sa.Column('d_c', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('connection', sa.Column('t_cf', sa.Numeric(precision=20, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 't_cf')
    op.drop_column('connection', 'd_c')
    op.drop_column('connection', 'steel_b')
    op.drop_column('connection', 'd_b')
    # ### end Alembic commands ###
