"""create connection + connection_global

Revision ID: 989b6f552169
Revises: 
Create Date: 2021-11-22 11:50:14.937205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b6f552169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experimental_program', sa.String(), nullable=False),
    sa.Column('date', sa.SmallInteger(), nullable=False),
    sa.Column('specimen_designation', sa.String(), nullable=False),
    sa.Column('northridge', sa.String(length=4), nullable=False),
    sa.Column('specimen_type', sa.String(), nullable=False),
    sa.Column('slab', sa.Boolean(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('section_b', sa.String(), nullable=False),
    sa.Column('section_c', sa.String(), nullable=False),
    sa.Column('t_dp', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('n_dp', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection_global',
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_drift_angle', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('actuator_force', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.PrimaryKeyConstraint('connection_id', 'id')
    )
    op.create_index(op.f('ix_connection_global_connection_id'), 'connection_global', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_global_connection_id'), table_name='connection_global')
    op.drop_table('connection_global')
    op.drop_table('connection')
    # ### end Alembic commands ###
